name:  insilichem
channels:
  - omnia
  - insilichem
  - rdkit
dependencies:
  - python=2.7.13
  - nomkl
  - cairo=1.12.18
  - certifi=2016.2.28
  - freetype=2.5.5
  - glib=2.50.2
  - icu=54.1
  - libgcc=5.2.0
  - libiconv=1.14
  - libpng=1.6.30
  - ncurses=6.0
  - numpy=1.11
  - pcre=8.39
  - pixman=0.32.6
  - readline=6.2
  - scipy=0.19
  - setuptools=27.2.0
  - sqlite=3.13.0
  - tk=8.5.18
  - nciplot
  - ambermini
  - rdkit